---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-exporter
  namespace: default 
  labels:
    app: chaos-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chaos-exporter
  template:
    metadata:
      labels:
        app: chaos-exporter 
    spec:
      containers:
      - name: chaos-exporter
        image: ksatchit/sample-chaos-exporter:ci 
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: chaos-exporter
  namespace: default
  labels:
    app: chaos-exporter
spec:
  ports:
  - port: 8080
    name: metrics
  selector:
    app: chaos-exporter 
